// FaqData.swift
//  MyOutdoorAgent
//  Created by CS on 14/09/22.

import Foundation

// -- FAQ
var faqData: [Section] = [
    Section(name: "My Account", expand: false, quesCategory: [
        QuesCategory(name: "How do I create an account?", expand: false, ansCategory: AnsCategory(name: "At the top of the website in the right-hand corner, you will see a green button that says \"LOGIN/REGISTER\". Click this button. You will now be directed to the login page. There are three choices to create an account. \n \n 1. Click the Facebook icon and sign in by connecting your Facebook account> \n 2. Click the Google+ icon and sign in by connecting your Google+ account \n 3. Click \"Register\", fill out the form on the page, agree to the Terms of Service and click \"Register\" \n \n You will receive a verification email after signing up. Your account will NOT be active until you have confirmed your email address by clicking the verification link sent. Can´t find the email? Make sure to check you spam/junk folder from help@myoutdooragent.com.")),
        QuesCategory(name: "How do I choose a password?", expand: false, ansCategory: AnsCategory(name: "All account passwords must be eight or more characters in length. Following are some tips to help you create a strong password: \n \n 1. Create a password with at least eight characters. Short passwords are easier to guess./li> \n 2. Combine letters, numbers and symbols. \n 3. Create a password that is easy for you to remember, but difficult for others to guess. Do not use your log-in name, your spouse’s name or your birthday. \n 4. Do not use a password that is hard to remember or must be written down in order to remember.")),
        QuesCategory(name: "How can i recieve text messages/mobile notifications?", expand: false, ansCategory: AnsCategory(name: "After creating and verifying your account, log in and click \"My Account\" in the top right-hand corner. From the drop-down menu, select \"Profile\". On the Account Settings section, beside \"Enable Mobile Notifications\", you will need to slide the toggle to the right side. A green check mark will appear. You have now enabled mobile notifications. \n **Note: You need to update your account setting information to include a mobile number before enabling mobile notifications.")),
        QuesCategory(name: "How do i update my information?", expand: false, ansCategory: AnsCategory(name: "1. Log into your account \n 2. Click the dropdown menu under \"My Account\" \n 3.Select \"Profile\" \n 4.Update your information in the boxes provided.")),
        QuesCategory(name: "How do i change my password?", expand: false, ansCategory: AnsCategory(name: "1.Log into your account \n 2. Click the dropdown menu under \"My Account\" \n 3. Select \"Profile\" \n 4. In the bottom, right-hand corner, click the red button that says \"RESET PASSWORD\" \n 5. You will receive an email including a link to reset your password.")),
        QuesCategory(name: "I've forgotten my password", expand: false, ansCategory: AnsCategory(name: "Have you forgotten your password? No problem. When logging into your account, select \"Forgot My Password\" in the right-hand corner of the login box. A link will be sent to your email for you to reset your password."))
    ]),
    Section(name: "Property Listings", expand: false, quesCategory:
                [QuesCategory(name: "What is the Property Listing/RUL?", expand: false, ansCategory: AnsCategory(name: "A Property Listing/Recreational License Unit (RLU) is the term used to identify an individual tract of land that may be licensed by an individual and/or a hunt club for recreational use, such as hunting. The RLU is defined by number of acres, boundaries, license length and other characteristics specific to the tract of land. An individual or hunt club may license more than one RLU.")),
                 QuesCategory(name: "How can I find available properties?", expand: false, ansCategory: AnsCategory(name: "In the top header, click \"SEARCH\". This will direct you to the available Property Listings and dynamic map. You can scroll through the available list of properties on the left-hand side, interact with the dynamic map, or filter your search by clicking \"Show Filters\", select your desired filters and click \"Apply\".")),
                 QuesCategory(name: "How do I filter my search?", expand: false, ansCategory: AnsCategory(name: "After navigating to the available Property Listings by clicking \"SEARCH\" in the top header, you can click filters in the top left-hand corner. A box will appear on the left side of the page with a number of filters for you to select from. After selecting the appropriate filters, click \"Apply\". The property listings will then be filtered down to the respective search.")),
                 QuesCategory(name: "Can i save my search", expand: false, ansCategory: AnsCategory(name: "Yes. After selecting the desired filters and clicking \"Apply\", You can click the green icon on the right- hand search. This will save your filter to your Account.")),
                 QuesCategory(name: "How do I find my saved searches", expand: false, ansCategory: AnsCategory(name: "Start by logging into your account. Then, click \"MY ACCOUNT\" in the top, right-hand corner of the page. From the drop-down menu, select \"Profile\". On the left-hand side, you will see two tabs. Select \"Saved Searches\". On this page, you can view your saved searches or delete previous saved searches you no longer wish to save.")),
                 QuesCategory(name: "How do I navigate the map?", expand: false, ansCategory: AnsCategory(name: "1. Click and drag the map to explore available Property Listings/Recreational License Units (RLUs). \n 2. Click on directional arrows to move the map. Click + to zoom in and – to zoom out. \n 3. Mouse over and click a marker to view Property Listing details and to License Now or Request Pre-Approval. \n 4. Use the Filters on the left-hand side to help you find the property you want. \n Note: Property Listing boundaries will be displayed on the map when you zoom in.")),
                 QuesCategory(name: "Can my license be terminated?", expand: false, ansCategory: AnsCategory(name: "Generally, at any time during the term, Agent shall have the right upon notice to Member to immediately revoke and terminate the license and the rights and privileges of licensees. For specific terms, see the license agreement.")),
                 QuesCategory(name: "Can i bring guests on a property?", expand: false, ansCategory: AnsCategory(name: "In order to bring additional guests or members onto the Property Listing/RLU, you will need to add each individual as an Invited Member to that specific property listing. That Invited Member will need to register their own My Outdoor Agent account and accept the license terms the specific Property Listing.")),
                 QuesCategory(name: "What about insurance?", expand: false, ansCategory: AnsCategory(name: "You will need to review the specific details of your property listing for the exact insurance")),
                 QuesCategory(name: "How soon can I access the property?", expand: false, ansCategory: AnsCategory(name: "You may not access the property listing until you have received a notification that your agreement has been legally executed and your license period begins.")),
                 QuesCategory(name: "Are motorized vehicles allowed?", expand: false, ansCategory: AnsCategory(name: "Please refer to your license agreement for information regarding motorized vehicle use on your Property Listing/RLU.")),
                 QuesCategory(name: "What is \"Request Pre-Approved\" for a license?", expand: false, ansCategory: AnsCategory(name: "Each Agent has the opportunity to review your application before confirming acceptance for licensing the property.")),
                 QuesCategory(name: "What happens after I have been pre-approved for a property/RLU?", expand: false, ansCategory: AnsCategory(name: "After you have executed your license agreement (signed and payed the fee), you will be immediately directed to the license details. On the top right side of the page, you will see a green button that says, \"INVITE MEMBERS\". After clicking this button, a pop-up box will appear. To invite new members, type or paste their emails below in the available text area that says, \"Enter email ID…\"")),
                 QuesCategory(name: "How do I add Members to a property?", expand: false, ansCategory: AnsCategory(name: "no")),
                 QuesCategory(name: "What information am I required to enter for Invited Members?", expand: false, ansCategory: AnsCategory(name: "You will need to provide an email address for your Invited Members when you invite them to an active Property Listing/RLU. Your members will be responsible for creating their own account and entering in their own details and accepting the terms of the license agreement.")),
                 QuesCategory(name: "How do I remove an Invited Member from an active Property Listing License?", expand: false, ansCategory: AnsCategory(name: "Invited Members may be deleted from the Property Listing License at any time. The owner of a Property Listing is the only person who can delete members. If you are a Property Listing owner, you can: \n 1. Log into your account \n 2. Click the dropdown menu under \"My Account\" \n 3. Select \"Profile\" \n 4. For the active property license, you would like to remove a member from, click the green button that says \"View Details\" under the respective property license. \n 5. In the top left-hand corner, you will see a list of your current members. \n 5. Select the member you would like to remove and click the red trashcan on the right-hand side of their name under the column \"Action\"")),
                 QuesCategory(name: "How do i view my license agreement?", expand: false, ansCategory: AnsCategory(name: "After you have reviewed, accepted the terms and paid your license fees, you will immediately be directed to the license details page. You can click the green button on the top of the page that says \"VIEW PROPERTY LICENSE AGREEMENT\" to download a copy of your license. Should you want to review your agreement at a later date, you can access this agreement at any time by: \n 1. Log into your account \n 2. Click the dropdown menu under \"My Account\" \n 3. Click \"Property License\" \n 4. Select the license you would like to view under \"My Active Property Licenses\" by clicking the green button \"View Details\" \n 5. Click the green button on the top of the page that says \"VIEW PROPERTY LICENSE AGREEMENT\". \n 6. Read, download or print the Property Listing agreement")),
                 QuesCategory(name: "How do i view my active properties?", expand: false, ansCategory: AnsCategory(name: "After logging into \"my account\", you will be directed to your account homepage. From there, click on the drop-down menu and click \"Licenses\". Active licenses are shown in their respective classes. For example, if you are the owner of a license, this license will be displayed under the box, \"My Licenses\". If you are a member of another property, this will be displayed under \"My Memberships\".")),
                ]),
    Section(name: "Paying Online", expand: false, quesCategory:
                [QuesCategory(name: "How do i pay my licencse fee?", expand: false, ansCategory: AnsCategory(name: "After you have been preapproved for a property listing, you will receive an email with further instructions. You will then need to: \n 1. Log back into your account \n 2. Click the drop-down menu under \"My Account\" \n 3. For the property listings that have been approved, there will be a green box that says \"License Now\" \n 4. Click \"View Details\" (this will direct your back to the property details page) \n 5. Click the green button that says \"License Now\" \n 6. Review the license agreement and scroll to the button \n 7. Click \"ACCEPT AND BUY NOW\" \n 8. This will direct you to our online payment platform")),
                 QuesCategory(name: "What type of payments are accepted", expand: false, ansCategory: AnsCategory(name: "We accept credit card and ACH payment methods."))
                ]),
    Section(name: "Support", expand: false, quesCategory:
                [QuesCategory(name: "How do I contact a property agent?", expand: false, ansCategory: AnsCategory(name: "To contact a property agent, you first need to select the property for which you have a question regarding. If this not an active license, navigate to the property details page. Scroll down. At the bottom of the page in the right-hand corner, you will see a box that says Property Listing Contact information. Note: not all Agents will list the same contact information .\n If you have already sent a message to a property agent previously, you can (after logging in) navigate to your message center by clicking \"Messages\" on the top header. This will direct you to your message center and display all previous messages with your property agent \n If you have a question for an ACTIVE property license, you have can: \n 1. Log in to your account \n 2. Click \"Messages\" in the top header \n 3. Any Property Listing you have an active Property Listing License for will automatically show up in your message center. You can contact the Property Listing Agent directly here. \n You will receive a verification email after signing up. Your account will NOT be active until you have confirmed your email address by clicking the verification link sent. Can´t find the email? Make sure to check you spam/junk folder from help@myoutdooragent.com.")),
                 QuesCategory(name: "Technical support", expand: false, ansCategory: AnsCategory(name: "Do you have technical questions regarding using the site? Please fill out our contact us form with your question. One of our team members should be back in touch with you within three (3) to five (5) business days"))
                ])
]


/*
 var faqData: [Section] = [
 Section(name: "Category 1", expand: false,
 quesCategory: [
 
 QuesCategory(name: "Category 1.1", expand: false, ansCategory: AnsCategory(name: "SubSubCategory 1.1.1")),
 
 QuesCategory(name: "Category 1.2", expand: false, ansCategory: AnsCategory(name: "SubSubCategory 1.2.1"))
 ]
 ),
 Section(name: "Category 2", expand: false,
 quesCategory: [
 
 QuesCategory(name: "Category 2.1", expand: false, ansCategory: AnsCategory(name: "SubSubCategory 2.1.1")),
 
 QuesCategory(name: "Category 2.2", expand: false, ansCategory: AnsCategory(name: "SubSubCategory 2.2.1"))
 ]
 )
 ]
 */
